name: Validacion automatica con github actions

#se va a ejecutar cuando haga un push a la rama main
on:
  push:
    branches:
      - main

#creara un trabajo que se llamara shellcheck 

jobs:
  shellcheck:
    runs-on: ubuntu-latest

#pasos que va a seguir el trabajo creado

#nombre del paso + el uso que se le da, lo que hace es copiar el codigo
    steps:
      - name: Clonar repo
        uses: actions/checkout@v4
#en este paso instalara shellcheck con los siguientes comandos

      - name: Instalar ShellCheck
        run: sudo apt-get update && sudo apt-get install -y shellcheck

#ejecutara shellcheck en el archivo de script en busca de errores

      - name: Validar script con ShellCheck
        run: shellcheck script.sh
